### ISSUE TITLE
error LAMA0222 after upgrading .net to 6.0.9 and metalama to 0.5.40-preview

### ISSUE THREAD

**Issue by martonx** [postsharp/Metalama#42]
Hi,

I get this error only at publishing asp.net core 6.0 project. Strange but build is ok, only publish is broken.

CSC : error LAMA0222: The compile-time project could not be compiled. In most cases, this is due to a problem in your code and can be diagnosed using the other reported errors. If, however, you believe this is due to a bug in Metalama, please report the issue and include diagnostic information available in '/tmp/Metalama/CompileTimeTroubleshooting/4.2.1013-preview/4a14a6a4-0e4a-490b-85a4-c2ea7e06316a'. [/src/Shox.Data/Shox.Data.csproj]
/tmp/Metalama/CompileTime/Shox.Comon/.netcoreapp6.0/69b5268905995169/4.2.1013-preview/LoggingAttribute_a9e028de02432a5a.cs(348,28): error CS0103: The name 'global' does not exist in the current context [/src/Shox.Data/Shox.Data.csproj]
/tmp/Metalama/CompileTime/Shox.Comon/.netcoreapp6.0/69b5268905995169/4.2.1013-preview/LoggingAttribute_a9e028de02432a5a.cs(348,87): error CS0103: The name 'global' does not exist in the current context [/src/Shox.Data/Shox.Data.csproj]

LoggingAttribute:

```
using Metalama.Framework.Aspects;
using Metalama.Framework.Code.SyntaxBuilders;

[assembly: AspectOrder(typeof(ToStringAttribute), typeof(LoggingAttribute))]
namespace Shox.Common.Logger;

public class LoggingAttribute : OverrideMethodAspect
{
	public override dynamic OverrideMethod()
	{
		try
		{
			var user = (meta.This.httpContextAccessor.HttpContext.User.Identity as ClaimsIdentity).Claims.FirstOrDefault(x => x.Type == "uid");
			var loggedInUserIdentity = !string.IsNullOrEmpty(user?.Value) ?
						               $" => by user: {user.Value}" :
						               string.Empty;
			
			var message = BuildInterpolatedString();
			message.AddExpression(loggedInUserIdentity);
			meta.This.logger.LogInformation(message.ToValue());

			var result = meta.Proceed();
			return result;
		}
		catch (Exception e)
		{
			var failureMessage = new InterpolatedStringBuilder();
			failureMessage.AddText(meta.Target.Method.Name);
			failureMessage.AddText(" failed: ");
			failureMessage.AddExpression(e.Message);
			meta.This.logger.LogInformation(failureMessage.ToValue());

			throw;
		}
	}

	protected InterpolatedStringBuilder BuildInterpolatedString()
	{
		var stringBuilder = new InterpolatedStringBuilder();

		stringBuilder.AddText($"{meta.Target.Type.Name}.{meta.Target.Method.Name}");

		stringBuilder.AddText("(");

		var i = meta.CompileTime(0);

		foreach (var prop in meta.Target.Parameters)
		{
			var comma = i > 0 ? ", " : "";

			if (i > 0)
				stringBuilder.AddText(", ");

			if (prop.Type.ToType() == typeof(string))
			{
				stringBuilder.AddText("'");
				stringBuilder.AddExpression(prop.Value);
				stringBuilder.AddText("'");
			}
			else
			{
				stringBuilder.AddText(prop.Name);
				stringBuilder.AddText(" : ");
				stringBuilder.AddExpression(prop.Value);
			}

			i++;
		}

		stringBuilder.AddText(")");

		return stringBuilder;
	}
}

using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Metalama.Framework.Code.SyntaxBuilders;
using Metalama.Framework.CodeFixes;

namespace Shox.Common.Logger;

[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
[CompileTime]
public class NotToStringAttribute : Attribute { }

[LiveTemplate]
public class ToStringAttribute : TypeAspect
{
	public override void BuildAspect(IAspectBuilder<INamedType> builder)
	{
		base.BuildAspect(builder);

		foreach (var field in builder.Target.FieldsAndProperties.Where(f => !f.IsStatic))
		{
			if (!field.Attributes.Any(a => a.Type.Is(typeof(NotToStringAttribute))))
			{
				builder.Diagnostics.Suggest(CodeFixFactory.AddAttribute(field, typeof(NotToStringAttribute), "Exclude from [ToString]"), field);
			}
		}

		if (builder.AspectInstance.Predecessors[0].Instance is IAttribute attribute)
		{
			builder.Diagnostics.Suggest(
				new CodeFix("Switch to manual implementation", codeFixBuilder => this.ImplementManually(codeFixBuilder, builder.Target)),
				attribute);
		}
	}

	[CompileTime]
	private async Task ImplementManually(ICodeActionBuilder builder, INamedType targetType)
	{
		await builder.ApplyAspectAsync(targetType, this);
		await builder.RemoveAttributesAsync(targetType, typeof(ToStringAttribute));
		await builder.RemoveAttributesAsync(targetType, typeof(NotToStringAttribute));
	}

	[Introduce(WhenExists = OverrideStrategy.Override, Name = "ToString")]
	public string IntroducedToString()
	{
		var stringBuilder = new InterpolatedStringBuilder();
		stringBuilder.AddText(meta.Target.Type.Name);
		stringBuilder.AddText(" ");

		var fields = meta.Target.Type.FieldsAndProperties.Where(f => !f.IsStatic).ToList();

		var i = meta.CompileTime(0);

		stringBuilder.AddText("{ ");
		foreach (var field in fields)
		{
			if (i > 0)
			{
				stringBuilder.AddText(", ");
			}

			stringBuilder.AddText(field.Name);
			stringBuilder.AddText(" : ");
			stringBuilder.AddExpression(JsonSerializer.Serialize(field.Invokers.Final.GetValue(meta.This)));

			i++;
		}
		stringBuilder.AddText(" }");

		return stringBuilder.ToValue();
	}
}
```

Please advice, how to fix this publish issue?

**Comment by PostSharpBot** [comment]
Hello @martonx, thank you for submitting this issue. We will try to get back to you as soon as possible.
Note to the PostSharp team, this ticket is being tracked in our dashboard under ID TP-31082.

**Comment by gfraiteur** [comment]
Could you please attach the file `/tmp/Metalama/CompileTime/Shox.Comon/.netcoreapp6.0/69b5268905995169/4.2.1013-preview/LoggingAttribute_a9e028de02432a5a.cs` ? It should contain some invalid C# code we have generated, and we could hopwfully see what was wrong.

**Comment by martonx** [comment]
@gfraiteur it works on my local windows machine. It is not working on our gitlab, docker based build system. I can't reach files inside gitlab and inside docker. I try to get this file somehow with devops.

**Comment by martonx** [comment]
Side note: when I downgraded only metalama Framework from 0.5.40-prev to the previous 0.5.37-prev it works again on gitlab docker build. So there must be some breaking changes through 0.5.37 to 0.5.40

**Comment by gfraiteur** [comment]
It's weird that it works locally but not on Docker. 
Let me know if you can find the temp file somehow.

**Comment by martonx** [comment]
[CompileTimeTroubleshooting.zip](https://github.com/postsharp/Metalama/files/9607981/CompileTimeTroubleshooting.zip)

Hello, finally we were able to extract the troubleshooting files. I zipped and auploaded here. I hope it helps to fix this issue.

Oh, and this is our DockerFile:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Shox.Web.Api/Shox.Web.Api.csproj", "Shox.Web.Api/"]
COPY ["Shox.Core/Shox.Core.csproj", "Shox.Core/"]
COPY ["Shox.Data/Shox.Data.csproj", "Shox.Data/"]
COPY ["Shox.Comon/Shox.Comon.csproj", "Shox.Comon/"]
RUN dotnet restore "Shox.Web.Api/Shox.Web.Api.csproj"
COPY . .
WORKDIR "/src/Shox.Web.Api"
RUN dotnet build "Shox.Web.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Shox.Web.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Shox.Web.Api.dll"]
```

Totally default asp.net core docker file. Build is ok, only publish breaks.

**Comment by gfraiteur** [comment]
It seems the offending cause may be ` $" => by user: {user.Value}" ` so turning the interpolated string into a `string.Format` may work around the problem in the meantime.

**Comment by wasyster** [comment]
We tried the workaround, but the publish failed again.

**Comment by gfraiteur** [comment]
I see.
It seems the line `stringBuilder.AddText($"{meta.Target.Type.Name}.{meta.Target.Method.Name}");` is also doing problems, so changing that to string.Format may work around the issue.
I will add a case to my test suite.

**Comment by wasyster** [comment]
Thank you, it solved the problem.

**Comment by wasyster** [comment]
Worked, thnx

**Comment by gfraiteur** [comment]
This should be solved in 0.5.41-preview.

**Comment by gfraiteur** [comment]
Reopening. Only the first issue is solved.

**Comment by martonx** [comment]
Thanks we are waiting the final fix. Anyway workaround works.

**Comment by gfraiteur** [comment]
Fixed in 0.5.44-preview.

**Comment by gfraiteur** [comment]
I can see it with the code you attached. I apologize for the back-and-forth. Next time I will ping you when the supplied code actually builds.

**Comment by gfraiteur** [comment]
Solved in 0.5.45-preview and this time your original code snippet works.
